spring:
  application:
    name: account-service

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---
spring:
  profiles:
    active: zone1
---

spring:
  profiles: zone1
eureka:
  instance:
    metadata-map:
      zone: zone1
    prefer-ip-address: true
    hostname: "localhost"

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
server:
  port: ${PORT:8091}

---

spring:
  profiles: zone2
eureka:
  instance:
    metadata-map:
      zone: zone2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
server:
  port: ${PORT:9091}