spring:
  application:
    name: gateway-service

server:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defautZone: http://localhost:8761/eureka/
    register-with-eureka: false

zuul:
  prefix: /api
  routes:
    account-service:
      path: /account/**
    customer-service:
      path: /customer/**
    order-service:
      path: /order/**
    product-service:
      path: /product/**

management:
  security:
    enabled: false