spring:
  application:
    name: customer-service

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---

spring:
  profiles:
    active: zone1

---

spring:
  profiles: zone1
eureka:
  instance:
    metadata-map:
      zone: zone1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
server:
  port: ${PORT:8092}

---

spring:
  profiles: zone2
eureka:
  instance:
    metadata-map:
      zone: zone2
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
      preferSameZoneEureka: true
server:
  port: ${PORT:9092}
