server:
  port: ${PORT:8889}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        monitor:
          github:
            enabled: true
        git:
          uri: https://github.com/DouglasGo8/spring-cloud-config-git-discovery.git
          username: ${github.username}
          password: ${github.password}
          cloneOnStart: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  security:
    enabled: false
